-- ============================================================================
-- DinkHub — Phase 2 Owner Invoices
-- ----------------------------------------------------------------------------
-- Weekly invoices billing each venue for booking fees collected during the
-- prior Mon–Sun period (Asia/Manila). Generated by the cron job
-- `/api/cron/weekly-invoices` and paid by the owner via single GCash transfer
-- to DinkHub's collection account (configured in `system_settings`).
--
-- Invariants (DB-enforced):
--   * One invoice per (venue, period_start)  — UNIQUE constraint
--   * Non-negative monetary amounts          — CHECK
--   * Strict status state machine            — enum
--   * Optimistic concurrency                 — version + bump trigger
-- Money is bigint centavos. Periods are timestamptz at Manila wall-clock
-- midnight on Mondays. RLS: owner reads own venues' invoices, admin reads all.
-- ============================================================================

create type public.owner_invoice_status as enum (
  'open',          -- generated, awaiting payment
  'submitted',     -- owner uploaded receipt; awaiting admin verification
  'verified',      -- admin verified receipt; settled
  'rejected',      -- admin rejected receipt; back to owner action
  'void'           -- cancelled (e.g., dispute resolution)
);

create table public.owner_invoices (
  id                       uuid primary key default gen_random_uuid(),
  venue_id                 uuid not null references public.venues(id) on delete restrict,
  period_start             timestamptz not null,        -- Mon 00:00 Manila (inclusive)
  period_end               timestamptz not null,        -- next Mon 00:00 Manila (exclusive)
  booking_count            integer not null check (booking_count >= 0),
  fees_centavos            bigint  not null check (fees_centavos >= 0),
  carryover_centavos       bigint  not null default 0 check (carryover_centavos >= 0),
  total_centavos           bigint  not null generated always as (fees_centavos + carryover_centavos) stored,
  due_date                 date    not null,
  status                   public.owner_invoice_status not null default 'open',

  -- Receipt details (populated when owner submits payment)
  receipt_image_path       text,
  receipt_hash             text,
  gcash_reference_number   text,
  amount_paid_centavos     bigint  check (amount_paid_centavos is null or amount_paid_centavos >= 0),
  submitted_at             timestamptz,
  submitted_by             uuid references public.profiles(id),

  -- Admin verification audit
  verified_at              timestamptz,
  verified_by              uuid references public.profiles(id),
  rejection_reason         text,

  version                  integer not null default 1,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),

  constraint owner_invoices_period_order check (period_end > period_start),
  constraint owner_invoices_unique_period unique (venue_id, period_start),
  -- Idempotency for receipt re-submission: same hash for same invoice = same upload
  constraint owner_invoices_unique_receipt unique (id, receipt_hash)
);

create index owner_invoices_venue_status_idx on public.owner_invoices (venue_id, status);
create index owner_invoices_status_due_idx   on public.owner_invoices (status, due_date);
create index owner_invoices_period_idx       on public.owner_invoices (period_start);

create trigger owner_invoices_bump_version before update on public.owner_invoices
  for each row execute function public.bump_version();

-- ----------------------------------------------------------------------------
-- RLS: default deny. Owners read their own venues' invoices; admins read all.
-- All writes go through SECURITY DEFINER service-role code paths (cron + admin
-- + owner submission action). No direct INSERT/UPDATE policies are granted.
-- ----------------------------------------------------------------------------
alter table public.owner_invoices enable row level security;

create policy owner_invoices_owner_read on public.owner_invoices
  for select to authenticated
  using (
    exists (
      select 1 from public.venues v
      where v.id = owner_invoices.venue_id
        and v.owner_id = auth.uid()
        and v.deleted_at is null
    )
  );

create policy owner_invoices_admin_read on public.owner_invoices
  for select to authenticated
  using (public.is_admin());
